#!/data/data/com.termux/files/usr/bin/env zsh

#XDG directory
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_RUNTIME_DIR="$ROOT/usr/tmp/runtime-$USER"

# General
export LC_ALL="${LC_ALL:-C.UTF-8}"
export LANG="${LANG:-C.UTF-8}"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GIT_CONFIG_GLOBAL="${XDG_CONFIG_HOME:-$HOME/.config}/git/config"
export EDITOR="nvim"
export SSH_CONFIG_DIR="${XDG_CONFIG_HOME}/ssh"
export STARSHIP_CONFIG="${XDG_CONFIG_HOME}/starship/starship.toml"
export GRCDIR=$XDG_CONFIG_HOME/globrc
export PATH="${XDG_CONFIG_HOME:-$HOME/.local/share}/cargo/bin:$PATH"

# export ZDOTDIR=$HOME
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export ZHOMEDIR=$HOME/.config/zsh
export ZDATADIR=$XDG_DATA_HOME/zsh
export ZCACHEDIR=$XDG_CACHE_HOME/zsh
# source $ZDOTDIR/.zshrc

export HELIX_RUNTIME="/data/data/com.termux/files/home/.config/helix/runtime"
# Zinit
# declare 
