#!/usr/bin/env  zsh

### Added by Zinit's installer
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit for \
    light-mode \
        zdharma-continuum/zinit-annex-as-monitor \
        zdharma-continuum/zinit-annex-bin-gem-node \
        zdharma-continuum/zinit-annex-patch-dl \
        zdharma-continuum/zinit-annex-rust

### End of Zinit's installer chunnk
### ZINIT CONFIG:
zinit for \
    light-mode \
        zsh-users/zsh-autosuggestions \
        zsh-users/zsh-syntax-highlighting \
        zdharma-continuum/fast-syntax-highlighting \
        zdharma-continuum/history-search-multi-word \

zinit ice as"null" from"gh-r" mv"starship -> $ZPFX/bin" bpick"*musl*" \
      atclone"starship init zsh > init.zsh; ./starship completions zsh > _starship" \
      atpull"%atclone" src"init.zsh"
zinit light starship/starship

zi ice as"null" from"gh-r" mv"zoxide -> $ZPFX/bin" \
      atclone"zoxide init zsh > init.zsh" \
      atpull"%atclone" src"init.zsh"
zi light ajeetdsouza/zoxide

zi ice as"null" from"gh-r" mv"atuin-*/atuin -> $ZPFX/bin" bpick"*musl.tar*" \
      atclone"atuin init zsh > init.zsh;rm -r atuin-" \
      atpull"%atclone" src"init.zsh"
zi load atuinsh/atuin

zi ice as"null" from"gh-r" \
      atclone"cp -rn fastfetch-*/usr/* $ZPFX;rm -rf fastfetch-*"
zi light fastfetch-cli/fastfetch

zi ice as"null" from"gh-r" mv"eza ->$ZPFX/bin"
zi light eza-community/eza

zi ice has'zoxide'
zi light z-shell/zsh-zoxide

zi ice wait lucid has'eza' atinit'AUTOCD=1'
zi light z-shell/zsh-eza



### Source zsh config
for file in $XDG_CONFIG_HOME/src/*; do
    source "$file"
done


