#!/data/data/com.termux/files/usr/bin/env dash
[ ! $(gh) ] && echo "please install gh-cli first!" &&read -r X
H=$(gh codespace | bat -r 3:25)
echo "$H"
while true; do
  j=$(stty size | awk '{print $NF}')
  i=0
  while [ "$i" -lt "$j" ]; do
    printf "-"
    i=$((i + 1))
  done
  printf "\033[0;33m%s\033[1;37m" "codespace : "
  read -r CMD
  case "$CMD" in
  exit | x | "$EOF") break ;;
  help | h) echo "$H" ;;
  *) gh codespace "$CMD"
     if [ "$CMD" = ssh ]; then
      gh codespace ls
     fi
    ;;

  esac
done
