#!/data/data/com.termux/files/usr/bin/env bash
export USER
USER=$(id -un)
# case "$-" in
# *i*)
#   if [ $SHLVL -eq 1 ]; then
#     login ~/.config/fastfetch/startup.sh
#   fi
#   ;;
# esac
# your bashrc settings come here...

if [[ -d ${XDG_CONFIG_HOME:-$HOME/.config}/sh.d ]]; then
  for file in "${XDG_CONFIG_HOME:-$HOME/.config}"/sh.d/*.sh; do
    source "$file"
  done
  for file in "${XDG_CONFIG_HOME:-$HOME/.config}"/sh.d/extra/*.sh; do
    source "$file"
  done
fi
if [ -f ~/.bash_history ] && [ -f ~/.history ];then
  rm ~/.bash_history
fi
